CREATE DATABASE IF NOT EXISTS elearning_db;
USE elearning_db;

CREATE TABLE IF NOT EXISTS DANHMUC (
    MaDM INT AUTO_INCREMENT PRIMARY KEY,
    TenDanhMuc VARCHAR(255) NOT NULL,
    IconURL VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS BAIHOC (
    MaBH INT AUTO_INCREMENT PRIMARY KEY,
    TenBH VARCHAR(255) NOT NULL,
    NoiDungBH TEXT,
    LinkURL VARCHAR(255),
    HinhAnh VARCHAR(255),
    NgayDang DATETIME DEFAULT CURRENT_TIMESTAMP,
    MaDM INT,
    FOREIGN KEY (MaDM) REFERENCES DANHMUC(MaDM) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS INTERACTIVE_LAB (
    MaTH INT AUTO_INCREMENT PRIMARY KEY,
    TenThucHanh VARCHAR(255) NOT NULL,
    MoTaThucHanh TEXT,
    TrangThaiBanDau TEXT,
    TrangThaiDung TEXT,
    GoiY TEXT,
    MaBH INT,
    FOREIGN KEY (MaBH) REFERENCES BAIHOC(MaBH) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TAINGUYEN (
    MaTaiNguyen INT AUTO_INCREMENT PRIMARY KEY,
    TenTaiNguyen VARCHAR(255) NOT NULL,
    LinkURL VARCHAR(255),
    DinhDang VARCHAR(50),
    DungLuong FLOAT,
    HinhAnhPreview VARCHAR(255),
    MoTa TEXT,
    MaBH INT,
    FOREIGN KEY (MaBH) REFERENCES BAIHOC(MaBH) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRACNGHIEM (
    MaTN INT AUTO_INCREMENT PRIMARY KEY,
    NoiDungCauHoi TEXT NOT NULL,
    HinhAnh VARCHAR(255),
    LoiGiaiThich TEXT,
    MaBH INT,
    FOREIGN KEY (MaBH) REFERENCES BAIHOC(MaBH) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DAPAN (
    MaDA INT AUTO_INCREMENT PRIMARY KEY,
    NoiDungDapAn VARCHAR(255) NOT NULL,
    IsCorrect BOOLEAN DEFAULT FALSE,
    MaTN INT,
    FOREIGN KEY (MaTN) REFERENCES TRACNGHIEM(MaTN) ON DELETE CASCADE
);

